import path from "node:path";

const EXTENSIONS_BY_LANGUAGE: Record<string, readonly string[]> = {
  javascript: ["js", "jsx", "mjs", "cjs", "es", "es6", "jake"],
  typescript: ["ts", "tsx", "mts", "cts"],
  vue: ["vue"],
  svelte: ["svelte"],
  astro: ["astro"],
  html: ["html", "htm", "xhtml", "shtml"],
  css: ["css", "pcss", "postcss"],
  scss: ["scss"],
  sass: ["sass"],
  less: ["less"],
  stylus: ["styl", "stylus"],
  python: ["py", "pyw", "pyi", "pyx", "pxd", "pxi", "py3"],
  ruby: ["rb", "rbw", "rake", "gemspec", "ru", "erb", "haml", "slim"],
  java: ["java", "jav"],
  kotlin: ["kt", "kts"],
  groovy: ["groovy", "gvy", "gy", "gsh", "gradle"],
  scala: ["scala", "sc", "sbt"],
  c: ["c", "h"],
  cpp: ["cc", "cpp", "cxx", "c++", "hh", "hpp", "hxx", "h++", "ipp", "inl", "tcc"],
  csharp: ["cs", "csx"],
  fsharp: ["fs", "fsx", "fsi"],
  visualbasic: ["vb", "vbs"],
  swift: ["swift"],
  objectivec: ["m", "mm"],
  dart: ["dart"],
  go: ["go"],
  rust: ["rs"],
  php: ["php", "php3", "php4", "php5", "php7", "php8", "phtml", "phps"],
  lua: ["lua"],
  perl: ["pl", "pm", "pod", "t", "psgi"],
  r: ["r", "rmd", "qmd"],
  julia: ["jl"],
  elixir: ["ex", "exs", "eex", "leex", "heex"],
  erlang: ["erl", "hrl", "escript"],
  haskell: ["hs", "lhs"],
  clojure: ["clj", "cljs", "cljc"],
  commonlisp: ["lisp", "lsp", "cl"],
  scheme: ["scm", "ss", "sld", "sls"],
  racket: ["rkt", "rktd", "rktl"],
  emacslisp: ["el"],
  ocaml: ["ml", "mli", "mll", "mly"],
  reason: ["re", "rei"],
  rescript: ["res", "resi"],
  elm: ["elm"],
  purescript: ["purs"],
  idris: ["idr", "lidr"],
  nim: ["nim", "nims", "nimble"],
  zig: ["zig", "zon"],
  crystal: ["cr"],
  vala: ["vala", "vapi"],
  fortran: ["f", "for", "f77", "f90", "f95", "f03", "f08", "fpp"],
  cobol: ["cob", "cbl", "cpy", "cobol"],
  pascal: ["pas", "pp", "lpr", "dpr", "dpk"],
  ada: ["adb", "ads", "ada"],
  d: ["d", "di"],
  assembly: ["asm", "s", "inc", "nasm", "masm"],
  shell: ["sh", "bash", "zsh", "fish", "ksh", "csh", "tcsh"],
  powershell: ["ps1", "psm1", "psd1"],
  batch: ["bat", "cmd"],
  sql: ["sql", "ddl", "dml", "psql", "pgsql", "mysql", "sqlite", "hql"],
  graphql: ["graphql", "gql", "graphqls"],
  protobuf: ["proto", "protodevel"],
  thrift: ["thrift"],
  capnproto: ["capnp"],
  flatbuffers: ["fbs"],
  solidity: ["sol"],
  vyper: ["vy"],
  move: ["move"],
  cadence: ["cdc"],
  tact: ["tact"],
  hcl: ["hcl", "tf", "tfvars", "nomad"],
  nix: ["nix"],
  dhall: ["dhall"],
  cue: ["cue"],
  cmake: ["cmake"],
  make: ["mk", "mak", "make"],
  bazel: ["bzl", "bazel"],
  meson: ["meson"],
  qml: ["qml", "qbs"],
  glsl: ["glsl", "vert", "frag", "geom", "tesc", "tese", "comp", "rgen", "rchit", "rmiss"],
  hlsl: ["hlsl", "fx", "fxh", "vsh", "psh"],
  wgsl: ["wgsl"],
  metal: ["metal"],
  cuda: ["cu", "cuh"],
  opencl: ["cl"],
  matlab: ["mlx"],
  verilog: ["v", "vh"],
  systemverilog: ["sv", "svh"],
  vhdl: ["vhd", "vhdl"],
  tcl: ["tcl", "tk", "itcl"],
  awk: ["awk"],
  sed: ["sed"],
  coffeescript: ["coffee", "litcoffee"],
  livescript: ["ls"],
  actionscript: ["as", "mxml"],
  apex: ["cls", "trigger"],
  abap: ["abap"],
  sas: ["sas"],
  stata: ["do", "ado", "mata"],
  wolfram: ["wl", "wls", "nb"],
  prolog: ["pro", "prolog", "plg"],
  smalltalk: ["st"],
  forth: ["fs", "fth", "4th"],
  basic: ["bas", "bi"],
  gdscript: ["gd"],
  gdshader: ["gdshader"],
  gdextension: ["gdextension"],
  shaderlab: ["shader", "compute", "cginc"],
  handlebars: ["hbs", "handlebars", "mustache"],
  twig: ["twig"],
  liquid: ["liquid"],
  ejs: ["ejs"],
  pug: ["pug", "jade"],
  jinja: ["jinja", "jinja2", "j2"],
  nunjucks: ["njk"],
  razor: ["razor", "cshtml", "vbhtml"],
  freemarker: ["ftl"],
  velocity: ["vm"],
  xaml: ["xaml", "axaml"],
  javafx: ["fxml"],
  appleui: ["storyboard", "xib"],
  androidresources: ["aidl"],
  cucumber: ["feature"],
  robotframework: ["robot", "resource"],
  llvm: ["ll"],
  webassembly: ["wat", "wast"],
  yacc: ["y", "yacc"],
  lex: ["l", "lex"],
  antlr: ["g", "g4"],
  rebol: ["r", "reb"],
  io: ["io"],
  pony: ["pony"],
  red: ["red", "reds"],
  chapel: ["chpl"],
  gleam: ["gleam"],
  mojo: ["mojo", "🔥"],
  grain: ["gr"],
  ballerina: ["bal"],
  hack: ["hack", "hh"],
  templ: ["templ"],
  v: ["vsh"],
  circom: ["circom"],
  ink: ["ink"],
  janet: ["janet"],
  koka: ["kk", "kki"],
  lean: ["lean"],
  agda: ["agda", "lagda"],
  coq: ["v"],
  isabelle: ["thy"],
  alloy: ["als"],
  spin: ["pml"],
  oz: ["oz"],
  mercury: ["m"],
  openedge: ["p", "w", "i"],
  xquery: ["xq", "xql", "xqm", "xquery"],
  xslt: ["xsl", "xslt"]
};

const LANGUAGE_BY_EXTENSION = new Map<string, string>();
for (const [language, extensions] of Object.entries(EXTENSIONS_BY_LANGUAGE)) {
  for (const extension of extensions) {
    const normalized = `.${extension.toLowerCase()}`;
    if (!LANGUAGE_BY_EXTENSION.has(normalized)) LANGUAGE_BY_EXTENSION.set(normalized, language);
  }
}

const LANGUAGE_BY_FILENAME: Record<string, string> = {
  dockerfile: "dockerfile",
  containerfile: "dockerfile",
  makefile: "make",
  gnumakefile: "make",
  "cmakelists.txt": "cmake",
  jenkinsfile: "groovy",
  vagrantfile: "ruby",
  rakefile: "ruby",
  gemfile: "ruby",
  podfile: "ruby",
  fastfile: "ruby",
  appfile: "ruby",
  dangerfile: "ruby",
  brewfile: "ruby",
  procfile: "procfile",
  justfile: "just",
  taskfile: "task",
  build: "bazel",
  workspace: "bazel",
  "meson.build": "meson",
  "meson_options.txt": "meson"
};

const EXCLUDED_SOURCE_FILE_PATTERNS = [
  /(^|\.)min\.(js|mjs|cjs|css)$/i,
  /\.map$/i,
  /(^|\.)(generated|g)\.[^.]+$/i,
  /(^|[-_.])(lock|lockfile)$/i,
  /^(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|composer\.lock|cargo\.lock|poetry\.lock|pipfile\.lock|gemfile\.lock|podfile\.lock|pubspec\.lock)$/i
];

export function languageForSemanticSource(relPath: string): string | null {
  const name = path.posix.basename(relPath);
  if (EXCLUDED_SOURCE_FILE_PATTERNS.some((pattern) => pattern.test(name))) return null;
  const byName = LANGUAGE_BY_FILENAME[name.toLowerCase()];
  if (byName) return byName;
  return LANGUAGE_BY_EXTENSION.get(path.posix.extname(name).toLowerCase()) ?? null;
}

